micronaut:
  application:
    name: orders
netty:
  default:
    allocator:
      max-order: 3

mongodb:
  uri: "mongodb://root:root@localhost:27017/ecommerce?authSource=admin&authMechanism=SCRAM-SHA-256&tls=false"
  cluster:
    server-selection-timeout: 2s

logger:
  levels:
    io.micronaut.retry: DEBUG
